[package]
name = "autofire"
version = "0.2.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
winapi = "0.3.9"
