[package]
name = "autofire"
version = "0.3.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
rfd = "0.14.1"
windows = { version = "0.58.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi"] }
