[package]
name = "autofire"
version = "0.1.1"
edition = "2021"

[dependencies]
enigo = "0.2.1"
gilrs = { version = "0.10.7", features = ["xinput"], default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
